### ISSUE TITLE
Proposal Response

### ISSUE THREAD

**Issue by jasonseminara** [echoechochamber/passionProjection#1]
I think this is great! 
Please provide a list of use cases and/or user stories so tht you can stay focused on the goal; possibly narrowing scope. It's better to ship a fully-functioning product with a limited feature set than a site that doesn't work.

**Comment by echoechochamber** [comment]
Absolutely - I will ship it to you before going to bed tonight. I'm going to try and do some strong wireframes too because I think the ux / ui will be important to the value of this app
